### ISSUE TITLE
Crash at the time of injection

### ISSUE THREAD

**Issue by JFdevel** [morganwall/War-Thunder-Offset-Dumper#6]
I did everything according to the instructions. There were no errors during assembly.
Used your injector
![image](https://user-images.githubusercontent.com/39263181/202531181-02bc9a7f-7acb-4e87-b363-292ffc93c4a3.png)

**Comment by morganwall** [comment]
The signatures are mostlikely outdated, as I haven't worked on this since it was pretty much released.

**Comment by JFdevel** [comment]
> The signatures are mostlikely outdated, as I haven't worked on this since it was pretty much released.

can you update it? Or tell me how I can update them myself.

**Comment by morganwall** [comment]
> can you update it?

I would, though I don't play War Thunder anymore, plus really busy with Uni atm.

>Or tell me how I can update them myself.

You're gonna need some knowledge of reverse engineering, and preferable IDA. I'd suggest looking up some tutorials and learning from them, too much for me to cover. Also I never really added that much to this due to lack of demand, plus I stopped playing the game very shortly after.
If I ever do return to the game, I'll likely update and improve this.

**Comment by JFdevel** [comment]
Thanks for the answer, good luck with your studies!
