### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by exotic-6666** [morganwall/War-Thunder-Offset-Dumper#7]
![image](https://user-images.githubusercontent.com/68249812/213655463-9fb7c7bc-45ff-466d-96bd-59c63cda489d.png)

Tried using process hacker and the one just for this dumper neither of them work!

**Comment by morganwall** [comment]
The signatures haven't been updated in quite a while, so is most likely due to that.

**Comment by exotic-6666** [comment]
How do I get new signatures

**Comment by exotic-6666** [comment]
How do I get new signatures?

**Comment by morganwall** [comment]
You're gonna need to learn some reverse engineering, along with a program like IDA Pro.
As this program is rn, it's usless for people who aren't already somewhat knowledgeable in gamehacking.

Anyway, I might update the signatures at some point, but I'm not promising anything as I've no interest in this game anymore.
Due to the error being known, and that I'm not planning on fixing it rn, I'm going to close the issue as any other conversatios would be out of the scope of the start reason.
